// get places
export const ACTION_GET_PLACES_STARTED = "GET_PLACES_STARTED";
export const ACTION_GET_PLACES_SUCCEEDED = "GET_PLACES_SUCCEEDED";
export const ACTION_GET_PLACES_FAILED = "GET_PLACES_FAILED";

// get events
export const ACTION_GET_EVENTS_STARTED = "GET_EVENTS_STARTED";
export const ACTION_GET_EVENTS_SUCCEEDED = "GET_EVENTS_SUCCEEDED";
export const ACTION_GET_EVENTS_FAILED = "GET_EVENTS_FAILED";

// get company
export const ACTION_GET_COMPANY_STARTED = "GET_COMPANY_STARTED";
export const ACTION_GET_COMPANY_SUCCEEDED = "GET_COMPANY_SUCCEEDED";
export const ACTION_GET_COMPANY_FAILED = "GET_COMPANY_FAILED";